name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Copy files to EC2
        run: |
          scp -r ./backend/my-app ec2-user@YOUR_EC2_PUBLIC_IP:/home/ec2-user/

      - name: SSH and restart server
        run: |
          ssh ec2-user@YOUR_EC2_PUBLIC_IP << 'EOF'
            cd /home/ec2-user/my-app
            ./gradlew bootRun --stop
            ./gradlew bootRun --args='--spring.profiles.active=prod' &
          EOF
